### ISSUE TITLE
About the Asset

### ISSUE THREAD

**Issue by duyongoc** [Heathro/Dungeon#1]
Hi sir,
The game looks interesting!
May I know the name of the asset package you are using in this project? ^^

**Comment by Heathro** [comment]
Hi. it is SyntyStudios low poly asset pack called Dungeon.

**Comment by duyongoc** [comment]
![image](https://github.com/user-attachments/assets/0f0919fc-f222-4f5c-b79e-80ad24eff44f)
I'm trying to import that package. But it seems like it's still missing..

**Comment by Heathro** [comment]
SyntyStudios also have a map "Dungeon Map". I divided rooms for scenes, so I believe there could be doors, which I made to close holes in map caused by cutting it. These are probably same assets but streched etc.

**Comment by Heathro** [comment]
Oh, I get it. you are looking on Prototyping scene. for this I used Free asset pack for prototyping fron SyntyStudios. these doors are just yellow frames to pretend to be doors/portals

**Comment by duyongoc** [comment]
![image](https://github.com/user-attachments/assets/2fdf75b0-a7e9-44dc-9ac5-450426b2ada3)
The scene in game is missing. You just share the code. i got it now
Thank you ^^

**Comment by Heathro** [comment]
I was buying "Dungeon Map", so I had to delete scenes, because all levels are designed by SyntyStudios and cost money. I didnt want to redistribute them. Sorry.

**Comment by duyongoc** [comment]
Hi Sir, 
Its okay. Its your project, its your code. I'm just asking. 
Thank you ^^
